version: '3.7'

services:
  api:
    container_name: eng_software_trab_final
    build:
      context: .
      target: development
      dockerfile: dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${API_PORT}:${API_PORT}
    env_file:
      - .env
    networks:
      - backend
    depends_on:
      - postgres
      - redis
  redis:
    container_name: eng_software_trab_final_redis
    image: redis
    ports:
      - 6379:6379
    command: redis-server --requirepass redis
    networks:
      - backend
  postgres:
    container_name: eng_software_trab_final_db
    image: postgres:13-alpine
    networks:
      - backend
    environment:
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
      POSTGRES_USER: ${TYPEORM_USERNAME}
      POSTGRES_DB: ${TYPEORM_DATABASE}
    ports:
      - ${TYPEORM_PORT}:${TYPEORM_PORT}
    volumes:
      - api_db_data:/var/lib/postgresql/data
networks:
  backend:
volumes:
  api_db_data: